version: "3.9"

services:
  consul:
    image: consul:1.15.4
    container_name: consul
    command: "agent -dev -client=0.0.0.0"
    ports:
      - "8500:8500"
    volumes:
      - consul_data:/consul/data
    networks:
      - nomad_net

  vault:
    image: hashicorp/vault:1.21
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    depends_on:
      - consul
    networks:
      - nomad_net

  nomad:
    image: hashicorp/nomad:latest
    container_name: nomad
    command: "agent -dev -bind=0.0.0.0 -network-interface=eth0"
    ports:
      - "4646:4646"
      - "4647:4647"
      - "4648:4648"
    depends_on:
      - consul
      - vault
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nomad_net

  terraform:
    image: hashicorp/terraform:1.9
    container_name: terraform
    working_dir: /workspace
    network_mode: host
    volumes:
      - ./terraform:/workspace
      - ./vault:/vault
    environment:
      VAULT_ADDR: http://localhost:8200
      VAULT_TOKEN: root
      CONSUL_HTTP_ADDR: http://localhost:8500
      NOMAD_ADDR: http://localhost:4646
    depends_on:
      - nomad
      - consul
      - vault

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CI_SERVER_URL=https://gitlab.com/
      - RUNNER_NAME=local-runner
      - RUNNER_EXECUTOR=docker
    networks:
      - nomad_net

  springboot-app:
    build:
      context: ./springboot-app
    container_name: springboot-app
    environment:
      - VAULT_TOKEN=root
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=appdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    depends_on:
      - consul
      - vault
      - postgres
    networks:
      - nomad_net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      # Avoid conflicts with host Postgres by mapping to 55432 on the host
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nomad_net

volumes:
  consul_data:
  gitlab_runner_data:
  postgres_data:


networks:
  nomad_net:
    driver: bridge
